# try:
#     print(2 / 2)

# except:
#     print("something went wrong")

# finally:
#     print("hence proved")    

# x = 10
# if x > 5:
#     raise Exception('x should not exceed 5. The value of x was: {}'.format(x))

# a = 12
# if a >= 30:
#     raise Exception("a should not exceed 30. The value of a was: {}".format(a))